version: '3'
services:
  myapp:
    build: 
      context: ./
    image: ryan/myapp:8
    environment: 
      - server_port=8080
      - "JVM_OPT=-server -Xmx4g -Xms4g -Xmn512m -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M -Xss1M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
    ports: 
      - 8083:8080
    cpu_count: 2
    mem_limit: 5gb
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   endpoint_mode: vip
  myapp2:
    image: ryan/myapp:8
    environment: 
      - server_port=8080
      - "JVM_OPT=-server -Xmx4g -Xms4g -Xmn512m -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=512M -Xss1M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
    ports: 
      - 8084:8080
    cpu_count: 2
    mem_limit: 3gb
    depends_on: 
      - myapp
  ng: 
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "8090:8090"
    links: 
      - myapp
      - myapp2
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  